Adds github nuget source step.

diff --git a/.github/workflows/release.yml b/.github/workflows/release.yml
--- a/.github/workflows/release.yml
+++ b/.github/workflows/release.yml
@@ -7,6 +7,14 @@ jobs:
   publish:
     runs-on: ubuntu-latest
     steps:
+    - name: Validate Version
+      run: |
+        VERSION=${GITHUB_REF_NAME#v}
+        if [[ ! "$VERSION" =~ ^[0-9]+\.[0-9]+\.[0-9]+(-[0-9A-Za-z-]+(\.[0-9A-Za-z-]+)*)?(\+[0-9A-Za-z-]+(\.[0-9A-Za-z-]+)*)?$ ]]; then
+          echo "Invalid semantic version: $VERSION"
+          exit 1
+        fi
+        echo "VERSION=$VERSION" >> $GITHUB_ENV
     - uses: actions/checkout@v4
     - name: Setup .NET
       uses: actions/setup-dotnet@v4
@@ -16,15 +24,10 @@ jobs:
       run: dotnet build --configuration Release
     - name: Test
       run: dotnet test --no-build --configuration Release --verbosity normal
-    - name: Validate Version
-      run: |
-        VERSION=${GITHUB_REF_NAME#v}
-        if [[ ! "$VERSION" =~ ^[0-9]+\.[0-9]+\.[0-9]+(-[0-9A-Za-z-]+(\.[0-9A-Za-z-]+)*)?(\+[0-9A-Za-z-]+(\.[0-9A-Za-z-]+)*)?$ ]]; then
-          echo "Invalid semantic version: $VERSION"
-          exit 1
-        fi
-        echo "VERSION=$VERSION" >> $GITHUB_ENV
+      if: (!contains(env.VERSION, '-'))
     - name: Pack
       run: dotnet pack --no-build --configuration Release /p:PackageVersion=${VERSION} --output ./nupkg
+    - name: Setup GitHub NuGet source
+      run: dotnet nuget add source --username sadicangel --password ${{ secrets.GITHUB_TOKEN }} --store-password-in-clear-text --name github "https://nuget.pkg.github.com/sadicangel/index.json"
     - name: Publish to GitHub
       run: dotnet nuget push ./nupkg/*.nupkg --source "github" --api-key ${{ secrets.GITHUB_TOKEN }}
